/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -k public/trano be.glb
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function TranoBe(props: any) {
  const { nodes, materials } = useGLTF("/trano be.glb") as any
  return (
    <group {...props} dispose={null}>
      <group name="4Story_Mat" position={[-0.05, 0, -0.06]} scale={0.35}>
        <mesh
          name="Cube024"
          geometry={nodes.Cube024.geometry}
          material={materials.Bricks}
        />
        <mesh
          name="Cube024_1"
          geometry={nodes.Cube024_1.geometry}
          material={materials.Main}
        />
        <mesh
          name="Cube024_2"
          geometry={nodes.Cube024_2.geometry}
          material={materials.Windows}
        />
        <mesh
          name="Cube024_3"
          geometry={nodes.Cube024_3.geometry}
          material={materials.Glass}
        />
        <mesh
          name="Cube024_4"
          geometry={nodes.Cube024_4.geometry}
          material={materials.Dark}
        />
        <mesh
          name="Cube024_5"
          geometry={nodes.Cube024_5.geometry}
          material={materials.White}
        />
        <mesh
          name="Cube024_6"
          geometry={nodes.Cube024_6.geometry}
          material={materials.Black}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/trano be.glb")
