/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -k public/trano.glb
*/
//@ts-nocheck
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function Trano(props) {
  const { nodes, materials } = useGLTF("/trano.glb")
  return (
    <group {...props} dispose={null}>
      <group name="trano" scale={0.2}>
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          name="Cube001_1"
          geometry={nodes.Cube001_1.geometry}
          material={materials["DarkWood.001"]}
        />
        <mesh
          name="Cube001_2"
          geometry={nodes.Cube001_2.geometry}
          material={materials["Dark.001"]}
        />
        <mesh
          name="Cube001_3"
          geometry={nodes.Cube001_3.geometry}
          material={materials["RoofBricks.001"]}
        />
        <mesh
          name="Cube001_4"
          geometry={nodes.Cube001_4.geometry}
          material={materials["Bricks.001"]}
        />
        <mesh
          name="Cube001_5"
          geometry={nodes.Cube001_5.geometry}
          material={materials["Main.001"]}
        />
        <mesh
          name="Cube001_6"
          geometry={nodes.Cube001_6.geometry}
          material={materials["White.001"]}
        />
        <mesh
          name="Cube001_7"
          geometry={nodes.Cube001_7.geometry}
          material={materials["Wood.001"]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/trano.glb")
