/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -k public/trano2.glb
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function Trano2(props: any) {
  const { nodes, materials } = useGLTF("/trano2.glb") as any
  return (
    <group {...props} dispose={null}>
      <group name="1Story_Mat" scale={0.26}>
        <mesh
          name="Cube040"
          geometry={nodes.Cube040.geometry}
          material={materials.DarkWood}
        />
        <mesh
          name="Cube040_1"
          geometry={nodes.Cube040_1.geometry}
          material={materials.Bricks}
        />
        <mesh
          name="Cube040_2"
          geometry={nodes.Cube040_2.geometry}
          material={materials.Main}
        />
        <mesh
          name="Cube040_3"
          geometry={nodes.Cube040_3.geometry}
          material={materials.Light}
        />
        <mesh
          name="Cube040_4"
          geometry={nodes.Cube040_4.geometry}
          material={materials.Dark}
        />
        <mesh
          name="Cube040_5"
          geometry={nodes.Cube040_5.geometry}
          material={materials.White}
        />
        <mesh
          name="Cube040_6"
          geometry={nodes.Cube040_6.geometry}
          material={materials.Wood}
        />
        <mesh
          name="Cube040_7"
          geometry={nodes.Cube040_7.geometry}
          material={materials.Glass}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/trano2.glb")
