stages:
  - build
  - deploy

build:
  image: node:16
  stage: build
  tags:
    - front
  before_script:
    - npm install --global pnpm
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  script:
    - pnpm build:compress
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  artifacts:
    paths:
      - dist.zip
    expire_in: 1 day
  only:
    - deploy
    - develop
deploy:
  stage: deploy
  tags:
    - front
  script:
    - |
      curl -X POST --form "file=@dist.zip" -H "Origin:https://madagascar.webcup.hodi.host" -H "Referer:https://madagascar.webcup.hodi.host" "https://madagascar.webcup.hodi.host/upload/zip"
  only:
    - deploy
