/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -k public/tps/center.glb src/Center.tsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useBakeLoader } from "../../utils/3d/useBakeLoader"

export function Center(props: any) {
  const { nodes, materials } = useGLTF("/tps/center.glb") as any
  const material = useBakeLoader("/tps/center.optimized.webp", false, {})
  return (
    <group {...props} dispose={null}>
      <group name="centerParent" position={[0, -0.033, -2.53]} scale={1.78}>
        <mesh
          name="center"
          geometry={nodes.center.geometry}
          material={material}
          position={[-0.87, -0.29, 0.88]}
        />
        <mesh
          name="fence"
          geometry={nodes.fence.geometry}
          material={material}
        />
      </group>
      <mesh
        name="fenceRight"
        geometry={nodes.fenceRight.geometry}
        material={material}
        position={[-3.18, -0.17, -2.41]}
        rotation={[0, 0, 0.04]}
      />
      <mesh
        name="fenceLeft"
        geometry={nodes.fenceLeft.geometry}
        material={material}
        position={[-3.18, -0.17, -2.61]}
        rotation={[0, 0, 0.04]}
      />
      <mesh
        name="planches"
        geometry={nodes.planches.geometry}
        material={material}
        position={[-3.18, -0.17, -2.5]}
        rotation={[0, 0, 0.04]}
      />
      <mesh
        name="fenceLeft001"
        geometry={nodes.fenceLeft001.geometry}
        material={material}
        position={[1.44, 0.01, -2.38]}
        rotation={[0, -0.07, 0.04]}
      />
      <mesh
        name="fenceRight001"
        geometry={nodes.fenceRight001.geometry}
        material={material}
        position={[1.44, 0.01, -2.38]}
        rotation={[0, -0.07, 0.04]}
      />
      <mesh
        name="planches001"
        geometry={nodes.planches001.geometry}
        material={material}
        position={[1.44, 0.01, -2.38]}
        rotation={[0, -0.07, 0.04]}
      />
      <mesh
        name="fenceLeft002"
        geometry={nodes.fenceLeft002.geometry}
        material={material}
        position={[-0.22, -0.17, -5.72]}
        rotation={[0.04, Math.PI / 2, 0]}
      />
      <mesh
        name="fenceRight002"
        geometry={nodes.fenceRight002.geometry}
        material={material}
        position={[-0.02, -0.17, -5.72]}
        rotation={[0.04, Math.PI / 2, 0]}
      />
      <mesh
        name="planches002"
        geometry={nodes.planches002.geometry}
        material={material}
        position={[-0.11, -0.17, -5.72]}
        rotation={[0.04, Math.PI / 2, 0]}
      />
    </group>
  )
}

useGLTF.preload("/tps/center.glb")
