/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -k public/tps/grass.glb src/Grass.tsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useBakeLoader } from "../../utils/3d/useBakeLoader"

export function Grass(props: any) {
  const { nodes, materials } = useGLTF("/tps/grass.glb") as any
  const material = useBakeLoader("/tps/grass.optimized.webp", false, {})
  return (
    <group {...props} dispose={null}>
      <group
        name="log_stack_parent"
        position={[-7.34, 0, 1.37]}
        rotation={[0, -0.73, 0]}
      >
        <mesh
          name="log_stack"
          geometry={nodes.log_stack.geometry}
          material={material}
          scale={0.7}
        />
      </group>
      <group name="tent_detailedOpenParent" position={[-8.92, 0, 1.64]}>
        <mesh
          name="tent_detailedOpen"
          geometry={nodes.tent_detailedOpen.geometry}
          material={material}
          position={[-0.08, 0, -0.07]}
        />
      </group>
      <group
        name="pirate_captain_8angles"
        position={[-8.44, 0, 1.02]}
        rotation={[0, 0.58, 0]}
        scale={0.28}
      >
        <mesh
          name="armLeft"
          geometry={nodes.armLeft.geometry}
          material={material}
          position={[-0.17, 0.7, 0]}
        />
        <mesh
          name="armRight"
          geometry={nodes.armRight.geometry}
          material={material}
          position={[0.17, 0.7, 0]}
        />
        <mesh
          name="body"
          geometry={nodes.body.geometry}
          material={material}
          position={[0, 0.41, 0]}
        />
        <mesh
          name="Group_122"
          geometry={nodes.Group_122.geometry}
          material={material}
          position={[0, 0.78, 0]}
        >
          <mesh
            name="Group_122001"
            geometry={nodes.Group_122001.geometry}
            material={material}
            position={[0.19, 0.21, -0.25]}
            rotation={[0.07, 0, 0]}
          />
        </mesh>
        <mesh
          name="legLeft"
          geometry={nodes.legLeft.geometry}
          material={material}
          position={[-0.16, 0.41, 0]}
        />
        <mesh
          name="legRight"
          geometry={nodes.legRight.geometry}
          material={material}
          position={[0.16, 0.41, 0]}
        />
      </group>
      <group name="log_stackLargeParent" position={[-10.42, 0, 1.48]}>
        <mesh
          name="log_stackLarge"
          geometry={nodes.log_stackLarge.geometry}
          material={material}
          position={[0.29, 0, -0.16]}
          rotation={[0, 0.51, 0]}
        />
      </group>
      <group name="statue" position={[-5.92, 0, 3.08]} rotation={[0, 0.31, 0]}>
        <mesh
          name="statue_head"
          geometry={nodes.statue_head.geometry}
          material={material}
          position={[0.39, 0, -0.3]}
        />
        <mesh
          name="statue_head001"
          geometry={nodes.statue_head001.geometry}
          material={material}
          position={[-0.43, 0, -0.32]}
          scale={0.79}
        />
        <mesh
          name="statue_head002"
          geometry={nodes.statue_head002.geometry}
          material={material}
          position={[-1.24, 0, -0.34]}
          scale={0.66}
        />
      </group>
      <group name="path" position={[-6.88, 0, -0.75]}>
        <mesh
          name="path_stone"
          geometry={nodes.path_stone.geometry}
          material={material}
          position={[-0.88, -0.02, 0.71]}
        />
        <mesh
          name="path_stone001"
          geometry={nodes.path_stone001.geometry}
          material={material}
          position={[0, -0.02, -0.16]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          name="path_stone002"
          geometry={nodes.path_stone002.geometry}
          material={material}
          position={[1.39, -0.02, -1.84]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          name="path_stoneCorner"
          geometry={nodes.path_stoneCorner.geometry}
          material={material}
          position={[-0.22, -0.02, 0.55]}
          rotation={[0, 1.37, 0]}
        />
        <mesh
          name="path_stoneCorner001"
          geometry={nodes.path_stoneCorner001.geometry}
          material={material}
          position={[0.18, -0.02, -1.55]}
          rotation={[Math.PI, -1.51, Math.PI]}
        />
      </group>
      <mesh
        name="plateformeGrass"
        geometry={nodes.plateformeGrass.geometry}
        material={material}
        position={[-8.71, 0, 0]}
        scale={4}
      />
      <mesh
        name="platform_grass"
        geometry={nodes.platform_grass.geometry}
        material={material}
        position={[-8.71, 0, 0]}
      />
      <mesh
        name="mushrooms"
        geometry={nodes.mushrooms.geometry}
        material={material}
        position={[-9.75, 0, 0.58]}
        scale={0.5}
      />
      <mesh
        name="crateGrass"
        geometry={nodes.crateGrass.geometry}
        material={material}
        position={[-8.72, 0.08, -0.03]}
        rotation={[0, -0.54, 0]}
        scale={0.74}
      />
      <mesh
        name="ship_wreck_8angles"
        geometry={nodes.ship_wreck_8angles.geometry}
        material={material}
        position={[-5.86, 0, -0.35]}
        rotation={[0, -0.47, -0.35]}
        scale={0.21}
      />
      <mesh
        name="sign"
        geometry={nodes.sign.geometry}
        material={material}
        position={[-5.84, 0, -1.94]}
        rotation={[0.56, -1.11, 0.36]}
        scale={1.42}
      />
      <mesh
        name="canon"
        geometry={nodes.canon.geometry}
        material={material}
        position={[-6.54, 0, 0.86]}
        rotation={[0, 0.66, 0]}
        scale={0.42}
      >
        <mesh
          name="barrel_2"
          geometry={nodes.barrel_2.geometry}
          material={material}
          position={[0, 0.45, -0.07]}
        />
        <mesh
          name="wheel_backLeft"
          geometry={nodes.wheel_backLeft.geometry}
          material={material}
          position={[-0.22, 0.13, 0.26]}
        />
        <mesh
          name="wheel_backRight"
          geometry={nodes.wheel_backRight.geometry}
          material={material}
          position={[0.22, 0.13, 0.26]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          name="wheel_frontLeft"
          geometry={nodes.wheel_frontLeft.geometry}
          material={material}
          position={[-0.22, 0.13, -0.2]}
        />
        <mesh
          name="wheel_frontRight"
          geometry={nodes.wheel_frontRight.geometry}
          material={material}
          position={[0.22, 0.13, -0.2]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </mesh>
      <mesh
        name="rocks"
        geometry={nodes.rocks.geometry}
        material={material}
        position={[-8.62, 0, 2.98]}
        rotation={[0, 0.71, 0]}
        scale={[1.57, 2.51, 1.57]}
      />
      <mesh
        name="stone_smallB"
        geometry={nodes.stone_smallB.geometry}
        material={material}
        position={[-10.58, -0.05, 2.91]}
      />
      <mesh
        name="stone_smallC"
        geometry={nodes.stone_smallC.geometry}
        material={material}
        position={[-10.61, -0.05, 2.54]}
      />
      <mesh
        name="stone_smallD"
        geometry={nodes.stone_smallD.geometry}
        material={material}
        position={[-10.94, -0.05, 2.66]}
      />
      <mesh
        name="stone_smallE"
        geometry={nodes.stone_smallE.geometry}
        material={material}
        position={[-10.83, -0.05, 3.05]}
      />
      <mesh
        name="stone_smallF"
        geometry={nodes.stone_smallF.geometry}
        material={material}
        position={[-11.25, -0.05, 2.89]}
      />
      <mesh
        name="stone_tallA"
        geometry={nodes.stone_tallA.geometry}
        material={material}
        position={[-9.78, 0, 2.94]}
        rotation={[0, 0.77, 0]}
        scale={0.86}
      />
      <mesh
        name="tree_cone"
        geometry={nodes.tree_cone.geometry}
        material={material}
        position={[-10.72, 0, -1.85]}
      />
      <mesh
        name="tree_cone001"
        geometry={nodes.tree_cone001.geometry}
        material={material}
        position={[-9.7, 0, -0.53]}
        scale={0.64}
      />
      <mesh
        name="tree_cone002"
        geometry={nodes.tree_cone002.geometry}
        material={material}
        position={[-11.6, 0, 0.53]}
      />
      <mesh
        name="tree_detailed"
        geometry={nodes.tree_detailed.geometry}
        material={material}
        position={[-11.78, -0.05, -1.15]}
      />
      <mesh
        name="tree_pineDefaultB"
        geometry={nodes.tree_pineDefaultB.geometry}
        material={material}
        position={[-11.25, -0.05, -3]}
      />
      <mesh
        name="tree_pineGroundA"
        geometry={nodes.tree_pineGroundA.geometry}
        material={material}
        position={[-9.93, 0, -1.19]}
      />
      <mesh
        name="tree_pineGroundB"
        geometry={nodes.tree_pineGroundB.geometry}
        material={material}
        position={[-11.35, 0, -0.6]}
      />
      <mesh
        name="tree_pineSmallA"
        geometry={nodes.tree_pineSmallA.geometry}
        material={material}
        position={[-9.34, 0, -1.93]}
      />
      <mesh
        name="tree_pineSmallA001"
        geometry={nodes.tree_pineSmallA001.geometry}
        material={material}
        position={[-10.48, 0, -0.07]}
      />
      <mesh
        name="tree_pineSmallB"
        geometry={nodes.tree_pineSmallB.geometry}
        material={material}
        position={[-8.19, -0.05, -2.83]}
      />
      <mesh
        name="tree_pineSmallC"
        geometry={nodes.tree_pineSmallC.geometry}
        material={material}
        position={[-8.45, 0, -1.92]}
      />
      <mesh
        name="tree_pineSmallC001"
        geometry={nodes.tree_pineSmallC001.geometry}
        material={material}
        position={[-5.64, 0, 1.37]}
      />
      <mesh
        name="tree_pineSmallD"
        geometry={nodes.tree_pineSmallD.geometry}
        material={material}
        position={[-10.46, 0, -2.68]}
      />
      <mesh
        name="tree_pineSmallD001"
        geometry={nodes.tree_pineSmallD001.geometry}
        material={material}
        position={[-5.93, 0, 1.93]}
        scale={0.76}
      />
      <mesh
        name="tree_pineTallA"
        geometry={nodes.tree_pineTallA.geometry}
        material={material}
        position={[-11.39, -0.05, -1.85]}
      />
      <mesh
        name="tree_pineTallB"
        geometry={nodes.tree_pineTallB.geometry}
        material={material}
        position={[-9.51, -0.05, -2.8]}
      />
      <mesh
        name="tree_pineTallC"
        geometry={nodes.tree_pineTallC.geometry}
        material={material}
        position={[-8.84, -0.05, -2.49]}
      />
      <mesh
        name="tree_pineTallC001"
        geometry={nodes.tree_pineTallC001.geometry}
        material={material}
        position={[-7.57, -0.05, -2.05]}
      />
      <mesh
        name="stump_old"
        geometry={nodes.stump_old.geometry}
        material={material}
        position={[-10.63, 0, -1.18]}
      />
      <mesh
        name="stump_round"
        geometry={nodes.stump_round.geometry}
        material={material}
        position={[-9.19, 0, -1.15]}
      />
      <mesh
        name="stump_square"
        geometry={nodes.stump_square.geometry}
        material={material}
        position={[-10.15, 0, -1.95]}
      />
      <mesh
        name="campfire_logs"
        geometry={nodes.campfire_logs.geometry}
        material={material}
        position={[-7.98, 0, 0.79]}
      />
      <mesh
        name="fence_planksDouble"
        geometry={nodes.fence_planksDouble.geometry}
        material={material}
        position={[-10.44, 0, 2.78]}
      />
    </group>
  )
}

useGLTF.preload("/tps/grass.glb")
