/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -k public/tps/snow.glb src/Snow.tsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useBakeLoader } from "../../utils/3d/useBakeLoader"
import { Vector3 } from "@react-three/fiber"

export function Snow(props: any) {
  const { nodes, materials } = useGLTF("/tps/snow.glb") as any
  const material = useBakeLoader("/tps/snow.optimized.webp", false, {})

  return (
    <group {...props} dispose={null}>
      <group name="path001" position={[6.69, 0.02, -0.88]}>
        <mesh
          name="path_stone003"
          geometry={nodes.path_stone003.geometry}
          material={material}
          position={[-1.01, -0.01, -1.28]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          name="path_stone004"
          geometry={nodes.path_stone004.geometry}
          material={material}
          position={[0.14, -0.01, 0.03]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          name="path_stone005"
          geometry={nodes.path_stone005.geometry}
          material={material}
          position={[1.01, 0.01, 1.28]}
        />
        <mesh
          name="path_stoneCorner002"
          geometry={nodes.path_stoneCorner002.geometry}
          material={material}
          position={[0.03, -0.01, -1.11]}
          rotation={[Math.PI, -1.51, Math.PI]}
        />
        <mesh
          name="path_stoneCorner003"
          geometry={nodes.path_stoneCorner003.geometry}
          material={material}
          position={[0.31, -0.01, 1.23]}
          rotation={[0, 1.37, 0]}
        />
      </group>
      <group name="tmpParent" position={[10.67, 0, 0.63]}>
        <mesh
          name="log_stackLarge001"
          geometry={nodes.log_stackLarge001.geometry}
          material={material}
          position={[0.31, 0, 0]}
          rotation={[0, -1.55, 0]}
        />
        <mesh
          name="log_stackLarge002"
          geometry={nodes.log_stackLarge002.geometry}
          material={material}
          position={[0.31, 0, 0.62]}
          rotation={[0, -1.55, 0]}
        />
      </group>
      <group name="tmpParent003" position={[7.2, 0, 2.54]}>
        <mesh
          name="statue_ring"
          geometry={nodes.statue_ring.geometry}
          material={material}
          position={[0.13, -0.05, -0.05]}
          rotation={[0, -0.54, 0]}
          scale={1.07}
        />
      </group>
      <group
        name="tmpParent004"
        position={[6.92, 0, 2.24]}
        rotation={[0, 1.06, 0]}
        scale={0.59}
      >
        <mesh
          name="statue_block"
          geometry={nodes.statue_block.geometry}
          material={material}
          position={[0.02, 0, 0.08]}
        />
      </group>
      <group
        name="tmpParent005"
        position={[7.81, 0, 2.8]}
        rotation={[0, 1.06, 0]}
        scale={0.59}
      >
        <mesh
          name="statue_block001"
          geometry={nodes.statue_block001.geometry}
          material={material}
          position={[0.03, 0, -0.19]}
        />
      </group>
      <mesh
        name="plateformeSnow"
        geometry={nodes.plateformeSnow.geometry}
        material={material}
        position={[8.65, 0, 0.41]}
        scale={4}
      />
      <mesh
        name="crateSnow"
        geometry={nodes.crateSnow.geometry}
        material={material}
        position={[8.64, 0.08, 0.38]}
        rotation={[0, -0.54, 0]}
        scale={0.74}
      />
      <mesh
        name="barrel002"
        geometry={nodes.barrel002.geometry}
        material={material}
        position={[10.91, 0, -0.6]}
      />
      <mesh
        name="barrel003"
        geometry={nodes.barrel003.geometry}
        material={material}
        position={[10.55, 0, -0.49]}
      />
      <mesh
        name="BirchTree_Dead_1_Cube100"
        geometry={nodes.BirchTree_Dead_1_Cube100.geometry}
        material={material}
        position={[11.23, 0, 0]}
      />
      <mesh
        name="BirchTree_Dead_Snow_5_Cube040"
        geometry={nodes.BirchTree_Dead_Snow_5_Cube040.geometry}
        material={material}
        position={[6.91, 0, 3.54]}
      />
      <mesh
        name="Bush_Snow_1_Cube131"
        geometry={nodes.Bush_Snow_1_Cube131.geometry}
        material={material}
        position={[9.76, 0.17, 2.99]}
      />
      <mesh
        name="Bush_Snow_2_Cube133"
        geometry={nodes.Bush_Snow_2_Cube133.geometry}
        material={material}
        position={[9.33, 0.23, 3.14]}
      />
      <mesh
        name="CommonTree_Dead_Snow_3_Cube001"
        geometry={nodes.CommonTree_Dead_Snow_3_Cube001.geometry}
        material={material}
        position={[10.13, 0, 3.46]}
      />
      <mesh
        name="CommonTree_Dead_Snow_3_Cube058"
        geometry={nodes.CommonTree_Dead_Snow_3_Cube058.geometry}
        material={material}
        position={[10.69, 0, -1.96]}
        scale={0.67}
      />
      <mesh
        name="CommonTree_Dead_Snow_4_Cube001"
        geometry={nodes.CommonTree_Dead_Snow_4_Cube001.geometry}
        material={material}
        position={[11.66, 0, -0.41]}
      />
      <mesh
        name="CommonTree_Dead_Snow_4_Cube059"
        geometry={nodes.CommonTree_Dead_Snow_4_Cube059.geometry}
        material={material}
        position={[9.14, 0, -2.52]}
      />
      <mesh
        name="CommonTree_Dead_Snow_5_Cube001"
        geometry={nodes.CommonTree_Dead_Snow_5_Cube001.geometry}
        material={material}
        position={[11.08, 0, 2.67]}
      />
      <mesh
        name="CommonTree_Snow_4_Cube136"
        geometry={nodes.CommonTree_Snow_4_Cube136.geometry}
        material={material}
        position={[5.76, 0, 2.32]}
      />
      <mesh
        name="flag"
        geometry={nodes.flag.geometry}
        material={material}
        position={[5.94, 0.98, -1.06]}
        scale={0.62}
      />
      <mesh
        name="PineTree_Snow_2_Cylinder079"
        geometry={nodes.PineTree_Snow_2_Cylinder079.geometry}
        material={material}
        position={[5.78, 0, 3.17]}
      />
      <mesh
        name="PineTree_Snow_5_Cylinder076"
        geometry={nodes.PineTree_Snow_5_Cylinder076.geometry}
        material={material}
        position={[8.47, 0, 3.49]}
      />
      <mesh
        name="Rock_Snow_1_Cube019"
        geometry={nodes.Rock_Snow_1_Cube019.geometry}
        material={material}
        position={[10.51, 0.09, 2.84]}
      />
      <mesh
        name="Rock_Snow_2_Cube000"
        geometry={nodes.Rock_Snow_2_Cube000.geometry}
        material={material}
        position={[10.89, 0.04, 2.21]}
      />
      <mesh
        name="Rock_Snow_3_Cube079"
        geometry={nodes.Rock_Snow_3_Cube079.geometry}
        material={material}
        position={[10.14, 0, -2.48]}
        rotation={[0, -0.96, 0]}
      />
      <mesh
        name="Rock_Snow_4_Cube077"
        geometry={nodes.Rock_Snow_4_Cube077.geometry}
        material={material}
        position={[10.9, 0.23, -2.59]}
        rotation={[Math.PI, -0.6, Math.PI]}
        scale={0.75}
      />
      <mesh
        name="Rock_Snow_5_Cube076"
        geometry={nodes.Rock_Snow_5_Cube076.geometry}
        material={material}
        position={[10.26, 0, -1.58]}
        scale={0.79}
      />
      <mesh
        name="Rock_Snow_6_Cube075"
        geometry={nodes.Rock_Snow_6_Cube075.geometry}
        material={material}
        position={[11.34, 0, -1.53]}
        scale={0.82}
      />
      <mesh
        name="tower"
        geometry={nodes.tower.geometry}
        material={material}
        position={[5.83, 0, -1.23]}
        rotation={[0, 1.14, 0]}
        scale={0.32}
      />
      <mesh
        name="TreeStump_Snow_Cylinder021"
        geometry={nodes.TreeStump_Snow_Cylinder021.geometry}
        material={material}
        position={[9.13, 0, -1.79]}
        scale={0.64}
      />
      <mesh
        name="wood-structure"
        geometry={nodes["wood-structure"].geometry}
        material={material}
        position={[8.65, 0, 0.41]}
        scale={1.33}
      />
      <mesh
        name="WoodLog_Snow_Cylinder019"
        geometry={nodes.WoodLog_Snow_Cylinder019.geometry}
        material={material}
        position={[10.11, 0, 2.16]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
      />
      <mesh
        name="barrel001"
        geometry={nodes.barrel001.geometry}
        material={material}
        position={[10.75, 0, -0.1]}
        scale={1.37}
      />
      <mesh
        name="platform_stone"
        geometry={nodes.platform_stone.geometry}
        material={material}
        position={[8.65, 0, 0.41]}
      />
      <mesh
        name="statue_column"
        geometry={nodes.statue_column.geometry}
        material={material}
        position={[5.38, 0, -2.78]}
      />
      <mesh
        name="statue_column001"
        geometry={nodes.statue_column001.geometry}
        material={material}
        position={[5.38, 0, -2.78]}
      />
    </group>
  )
}

useGLTF.preload("/tps/snow.glb")
