import { useGLTF } from "@react-three/drei"
import { MeshCollider, RigidBody, useRapier } from "@react-three/rapier"

export function Tower(props: any) {
  const { nodes, materials } = useGLTF("/tower.glb") as any
  return (
    <group {...props} dispose={null}>
      <MeshCollider type="cuboid">
        <group visible={false}>
          <mesh
            name="ground"
            geometry={nodes.ground.geometry}
            material={nodes.ground.material}
          />
          <mesh
            name="bi-collider016"
            geometry={nodes["bi-collider016"].geometry}
            material={nodes["bi-collider016"].material}
            position={[-3.46, 1.74, -0.59]}
            rotation={[-0.56, 0, 0]}
            scale={[1, 1.04, 1.09]}
          />
          <mesh
            name="bi-collider017"
            geometry={nodes["bi-collider017"].geometry}
            material={nodes["bi-collider017"].material}
            position={[3.61, 4.81, -0.46]}
            rotation={[-2.58, 0, -Math.PI]}
            scale={[1, 1.04, 1.09]}
          />
          <mesh
            name="bi-collider"
            geometry={nodes["bi-collider"].geometry}
            material={nodes["bi-collider"].material}
            position={[3.61, 7.75, -0.46]}
            rotation={[-2.58, 0, -Math.PI]}
            scale={[1, 1.04, 1.09]}
          />
          <mesh
            name="bi-collider018"
            geometry={nodes["bi-collider018"].geometry}
            material={materials.building_02}
          />
          <mesh
            name="bi-collider010"
            geometry={nodes["bi-collider010"].geometry}
            material={nodes["bi-collider010"].material}
            position={[-4.16, 6.1, 0.56]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="bi-collider001"
            geometry={nodes["bi-collider001"].geometry}
            material={nodes["bi-collider001"].material}
            position={[4.16, 6.1, 0.12]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="bi-collider002"
            geometry={nodes["bi-collider002"].geometry}
            material={nodes["bi-collider002"].material}
            position={[2.9, 7.47, -4.1]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.75, 1, 0.36]}
          />
          <mesh
            name="bi-collider003"
            geometry={nodes["bi-collider003"].geometry}
            material={nodes["bi-collider003"].material}
            position={[1.6, 10.37, -3.55]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="bi-collider004"
            geometry={nodes["bi-collider004"].geometry}
            material={nodes["bi-collider004"].material}
            position={[-1.31, 10.28, -2.98]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            name="bi-collider005"
            geometry={nodes["bi-collider005"].geometry}
            material={nodes["bi-collider005"].material}
            position={[-1.31, 10.28, 3.01]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            name="bi-collider006"
            geometry={nodes["bi-collider006"].geometry}
            material={nodes["bi-collider006"].material}
            position={[1.6, 10.37, 3.6]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="bi-collider007"
            geometry={nodes["bi-collider007"].geometry}
            material={nodes["bi-collider007"].material}
            position={[2.9, 7.47, 4.15]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.75, 1, 0.36]}
          />
          <mesh
            name="bi-collider008"
            geometry={nodes["bi-collider008"].geometry}
            material={nodes["bi-collider008"].material}
            position={[1.6, 4.41, 3.6]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="bi-collider009"
            geometry={nodes["bi-collider009"].geometry}
            material={nodes["bi-collider009"].material}
            position={[-3.39, 4.46, 2.89]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            name="bi-collider015"
            geometry={nodes["bi-collider015"].geometry}
            material={materials.building_02}
            position={[-2.85, 4.13, -1.14]}
          />
          <mesh
            name="bi-collider011"
            geometry={nodes["bi-collider011"].geometry}
            material={materials.building_02}
            position={[-2.9, 1.92, 0.36]}
          />
          <mesh
            name="bi-collider012"
            geometry={nodes["bi-collider012"].geometry}
            material={materials.building_02}
            position={[2.7, 1.41, -2.62]}
          />
          <mesh
            name="bi-collider013"
            geometry={nodes["bi-collider013"].geometry}
            material={nodes["bi-collider013"].material}
            position={[1.6, 7.1, -3.55]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="bi-collider014"
            geometry={nodes["bi-collider014"].geometry}
            material={nodes["bi-collider014"].material}
            position={[1.6, 4.16, -3.55]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="bi-collider019"
            geometry={nodes["bi-collider019"].geometry}
            material={materials.building_02}
            position={[0.05, 3.12, -0.51]}
          />
          <group name="bi-collider020" position={[-1.03, 6.17, 0.39]}>
            <mesh
              name="Cube155"
              geometry={nodes.Cube155.geometry}
              material={materials.building_02}
            />
            <mesh
              name="Cube155_1"
              geometry={nodes.Cube155_1.geometry}
              material={materials["Material.039"]}
            />
          </group>
          <mesh
            name="bi-collider021"
            geometry={nodes["bi-collider021"].geometry}
            material={materials.building_02}
            position={[-0.58, 9.07, 0.01]}
          />
          <mesh
            name="bi-collider022"
            geometry={nodes["bi-collider022"].geometry}
            material={nodes["bi-collider022"].material}
            position={[-1.2, 7.11, 4.15]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            name="bi-collider023"
            geometry={nodes["bi-collider023"].geometry}
            material={nodes["bi-collider023"].material}
            position={[-0.7, 7.09, -4.1]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.19, 1, 0.58]}
          />
        </group>
        <mesh
          name="bv_collider_floor001"
          geometry={nodes.bv_collider_floor001.geometry}
          material={materials.tohatra}
        />
        <mesh
          name="bv_collider_floor002"
          geometry={nodes.bv_collider_floor002.geometry}
          material={materials.tohatra}
        />
        <mesh
          name="bv_collider_floor003"
          geometry={nodes.bv_collider_floor003.geometry}
          material={materials.tohatra}
        />
        <mesh
          name="bv_collider_floor004"
          geometry={nodes.bv_collider_floor004.geometry}
          material={materials.tohatra}
        />
        <mesh
          name="bv_collider001"
          geometry={nodes.bv_collider001.geometry}
          material={materials.wall}
        />
        <mesh
          name="bv_collider002"
          geometry={nodes.bv_collider002.geometry}
          material={materials.wall}
        />
        <mesh
          name="bv_collider003"
          geometry={nodes.bv_collider003.geometry}
          material={materials.wall}
        />
        <mesh
          name="bv_collider004"
          geometry={nodes.bv_collider004.geometry}
          material={materials.wall}
        />
        <mesh
          name="bv_collider005"
          geometry={nodes.bv_collider005.geometry}
          material={materials.wall}
        />
        <mesh
          name="bv_collider006"
          geometry={nodes.bv_collider006.geometry}
          material={materials.tohatra}
        />
        <mesh
          name="bv_collider007"
          geometry={nodes.bv_collider007.geometry}
          material={materials.wall}
        />
        <mesh
          name="bv_collider008"
          geometry={nodes.bv_collider008.geometry}
          material={materials.wall}
        />
        <mesh
          name="bv_collider_floor"
          geometry={nodes.bv_collider_floor.geometry}
          material={materials.tohatra}
        />
        <mesh
          name="bv_collider014"
          geometry={nodes.bv_collider014.geometry}
          material={materials.wall}
        />
      </MeshCollider>
      <mesh
        name="Cube001"
        geometry={nodes.Cube001.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube002"
        geometry={nodes.Cube002.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube003"
        geometry={nodes.Cube003.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube004"
        geometry={nodes.Cube004.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube005"
        geometry={nodes.Cube005.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube006"
        geometry={nodes.Cube006.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube007"
        geometry={nodes.Cube007.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube008"
        geometry={nodes.Cube008.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube009"
        geometry={nodes.Cube009.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube010"
        geometry={nodes.Cube010.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube011"
        geometry={nodes.Cube011.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube012"
        geometry={nodes.Cube012.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube013"
        geometry={nodes.Cube013.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube014"
        geometry={nodes.Cube014.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube015"
        geometry={nodes.Cube015.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube016"
        geometry={nodes.Cube016.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube017"
        geometry={nodes.Cube017.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube018"
        geometry={nodes.Cube018.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube019"
        geometry={nodes.Cube019.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube021"
        geometry={nodes.Cube021.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube022"
        geometry={nodes.Cube022.geometry}
        material={materials.Gals}
      />
      <mesh
        name="Cube023"
        geometry={nodes.Cube023.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube024"
        geometry={nodes.Cube024.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube025"
        geometry={nodes.Cube025.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube026"
        geometry={nodes.Cube026.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube027"
        geometry={nodes.Cube027.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube028"
        geometry={nodes.Cube028.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube029"
        geometry={nodes.Cube029.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube030"
        geometry={nodes.Cube030.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube031"
        geometry={nodes.Cube031.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube032"
        geometry={nodes.Cube032.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube033"
        geometry={nodes.Cube033.geometry}
        material={materials.tohatra}
      />
      <mesh
        name="Cube034"
        geometry={nodes.Cube034.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube035"
        geometry={nodes.Cube035.geometry}
        material={materials["Material.037"]}
      />
      <mesh
        name="Cube038"
        geometry={nodes.Cube038.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube039"
        geometry={nodes.Cube039.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube040"
        geometry={nodes.Cube040.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube041"
        geometry={nodes.Cube041.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube042"
        geometry={nodes.Cube042.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube043"
        geometry={nodes.Cube043.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube044"
        geometry={nodes.Cube044.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube045"
        geometry={nodes.Cube045.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube046"
        geometry={nodes.Cube046.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube047"
        geometry={nodes.Cube047.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube048"
        geometry={nodes.Cube048.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube049"
        geometry={nodes.Cube049.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube050"
        geometry={nodes.Cube050.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube051"
        geometry={nodes.Cube051.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube052"
        geometry={nodes.Cube052.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube053"
        geometry={nodes.Cube053.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube054"
        geometry={nodes.Cube054.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube055"
        geometry={nodes.Cube055.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube056"
        geometry={nodes.Cube056.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube057"
        geometry={nodes.Cube057.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube058"
        geometry={nodes.Cube058.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube059"
        geometry={nodes.Cube059.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube060"
        geometry={nodes.Cube060.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube061"
        geometry={nodes.Cube061.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube062"
        geometry={nodes.Cube062.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube063"
        geometry={nodes.Cube063.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube064"
        geometry={nodes.Cube064.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube065"
        geometry={nodes.Cube065.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube066"
        geometry={nodes.Cube066.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube067"
        geometry={nodes.Cube067.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube068"
        geometry={nodes.Cube068.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube069"
        geometry={nodes.Cube069.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube070"
        geometry={nodes.Cube070.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube071"
        geometry={nodes.Cube071.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube072"
        geometry={nodes.Cube072.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube073"
        geometry={nodes.Cube073.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube074"
        geometry={nodes.Cube074.geometry}
        material={materials.tohatra}
      />
      <mesh
        name="Cube076"
        geometry={nodes.Cube076.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube077"
        geometry={nodes.Cube077.geometry}
        material={materials.tohatra}
      />
      <mesh
        name="Cube078"
        geometry={nodes.Cube078.geometry}
        material={materials.tohatra}
      />
      <mesh
        name="Cube079"
        geometry={nodes.Cube079.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube080"
        geometry={nodes.Cube080.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube081"
        geometry={nodes.Cube081.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube083"
        geometry={nodes.Cube083.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube084"
        geometry={nodes.Cube084.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube086"
        geometry={nodes.Cube086.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube087"
        geometry={nodes.Cube087.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube088"
        geometry={nodes.Cube088.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube089"
        geometry={nodes.Cube089.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube090"
        geometry={nodes.Cube090.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube091"
        geometry={nodes.Cube091.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube092"
        geometry={nodes.Cube092.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube093"
        geometry={nodes.Cube093.geometry}
        material={materials.building_02}
      />
      <mesh
        name="Cube094"
        geometry={nodes.Cube094.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube095"
        geometry={nodes.Cube095.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube096"
        geometry={nodes.Cube096.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube097"
        geometry={nodes.Cube097.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube098"
        geometry={nodes.Cube098.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube099"
        geometry={nodes.Cube099.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube100"
        geometry={nodes.Cube100.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube101"
        geometry={nodes.Cube101.geometry}
        material={materials.wood2}
      />
      <mesh
        name="Cube102"
        geometry={nodes.Cube102.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube103"
        geometry={nodes.Cube103.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube104"
        geometry={nodes.Cube104.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube105"
        geometry={nodes.Cube105.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube106"
        geometry={nodes.Cube106.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube107"
        geometry={nodes.Cube107.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube108"
        geometry={nodes.Cube108.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube109"
        geometry={nodes.Cube109.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube110"
        geometry={nodes.Cube110.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube111"
        geometry={nodes.Cube111.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube112"
        geometry={nodes.Cube112.geometry}
        material={materials.tohatra}
      />
      <mesh
        name="Cube113"
        geometry={nodes.Cube113.geometry}
        material={materials.tohatra}
      />
      <mesh
        name="Cube115"
        geometry={nodes.Cube115.geometry}
        material={materials.building_02}
      />
      <mesh
        name="Cube116"
        geometry={nodes.Cube116.geometry}
        material={materials.tohatra}
      />
      <mesh
        name="Cube119"
        geometry={nodes.Cube119.geometry}
        material={materials.tohatra}
      />
      <mesh
        name="Cube120"
        geometry={nodes.Cube120.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube121"
        geometry={nodes.Cube121.geometry}
        material={materials.wood}
      />
      <mesh
        name="Cube123"
        geometry={nodes.Cube123.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube124"
        geometry={nodes.Cube124.geometry}
        material={materials.building_02}
      />
      <mesh
        name="Cube125"
        geometry={nodes.Cube125.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube126"
        geometry={nodes.Cube126.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube127"
        geometry={nodes.Cube127.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube128"
        geometry={nodes.Cube128.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube130"
        geometry={nodes.Cube130.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube131"
        geometry={nodes.Cube131.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube132"
        geometry={nodes.Cube132.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube134"
        geometry={nodes.Cube134.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube135"
        geometry={nodes.Cube135.geometry}
        material={materials.wall}
      />
      <mesh
        name="bv_collider"
        geometry={nodes.bv_collider.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube137"
        geometry={nodes.Cube137.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube138"
        geometry={nodes.Cube138.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube139"
        geometry={nodes.Cube139.geometry}
        material={materials.Gals}
      />
      <mesh
        name="Cube140"
        geometry={nodes.Cube140.geometry}
        material={materials.Gals}
      />
      <mesh
        name="Cube141"
        geometry={nodes.Cube141.geometry}
        material={materials.Gals}
      />
      <mesh
        name="Cube088_1"
        geometry={nodes.Cube088_1.geometry}
        material={materials.wall}
      />
      <mesh
        name="Cube088_2"
        geometry={nodes.Cube088_2.geometry}
        material={materials.tohatra}
      />
    </group>
  )
}

useGLTF.preload("/tower.glb")
